import { createClient } from '@supabase/supabase-js'
import { Database } from '../src/lib/database.types'

const supabase = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

type SpaceInsert = Database['public']['Tables']['spaces']['Insert']

const SPACES: SpaceInsert[] = [
  {
    slug: 'idea-london',
    name: 'IDEA London',
    strapline: "UCL Engineering's space for events and coworking",
    area: 'Shoreditch',
    access_type: 'members',
    crowd_tags: ['founders', 'researchers', 'techies'],
    tags: ['coworking', 'events', 'lab'],
    website: 'https://www.idealondon.co.uk',
    featured: false,
  },
  {
    slug: 'scale-space',
    name: 'Scale Space',
    strapline: 'Lab and office space from Imperial College and Blenheim Chalcot',
    area: 'White City',
    access_type: 'members',
    crowd_tags: ['researchers', 'founders', 'techies'],
    tags: ['coworking', 'lab'],
    website: 'https://www.scalespace.co.uk',
    featured: false,
  },
  {
    slug: 'the-tower',
    name: 'The Tower',
    strapline: "Coworking and events in King's Cross",
    area: "King's Cross",
    access_type: 'members',
    crowd_tags: ['founders', 'techies'],
    tags: ['coworking', 'events'],
    website: 'https://startuptower.notion.site',
    featured: false,
  },
  {
    slug: 'sustainable-ventures',
    name: 'Sustainable Ventures',
    strapline: 'Climate tech coworking and community',
    area: 'Waterloo',
    access_type: 'members',
    crowd_tags: ['founders', 'researchers'],
    tags: ['coworking', 'events'],
    website: 'https://www.sustainableventures.co.uk',
    featured: false,
  },
  {
    slug: 'london-ai-hub',
    name: 'London AI Hub',
    strapline: 'Community events and coworking in Techspace Farringdon',
    area: 'Farringdon',
    access_type: 'members',
    crowd_tags: ['researchers', 'techies', 'founders'],
    tags: ['coworking', 'events'],
    website: 'https://www.londonaihub.co.uk',
    featured: false,
  },
  {
    slug: 'telos-house',
    name: 'Telos House',
    strapline: "Members space at King's Cross",
    area: "King's Cross",
    access_type: 'invite',
    crowd_tags: ['founders', 'operators'],
    tags: ['members club', 'coworking'],
    website: 'https://www.teloshouse.com',
    featured: false,
  },
  {
    slug: 'victoria-house',
    name: 'Victoria House',
    strapline: 'Biotech labs and event space housing the BioIndustry Association',
    area: 'Bloomsbury',
    access_type: 'members',
    crowd_tags: ['researchers', 'founders'],
    tags: ['lab', 'events', 'coworking'],
    website: 'https://victoriahouselondon.com',
    featured: false,
  },
  {
    slug: 'makerversity',
    name: 'Makerversity',
    strapline: 'Maker and creative studio space in Somerset House',
    area: 'Holborn',
    access_type: 'members',
    crowd_tags: ['designers', 'artists', 'techies'],
    tags: ['studio', 'lab', 'coworking'],
    website: 'https://www.makerversity.org',
    featured: false,
  },
  {
    slug: 'antler-techspace-aldgate',
    name: 'Antler (Techspace Aldgate)',
    strapline: 'Pre-idea accelerator based in Techspace Aldgate',
    area: 'Aldgate',
    access_type: 'invite',
    crowd_tags: ['founders'],
    tags: ['studio', 'events'],
    featured: false,
  },
  {
    slug: 'the-gramophone-works',
    name: 'The Gramophone Works',
    strapline: '60,000 sqft creative campus, home to Kindred Studios',
    area: 'Notting Hill',
    access_type: 'members',
    crowd_tags: ['artists', 'designers', 'founders'],
    tags: ['studio', 'events', 'coworking'],
    website: 'https://thegramophoneworks.com',
    featured: false,
  },
  {
    slug: 'entrepreneurs-first',
    name: 'Entrepreneurs First',
    strapline: 'Pre-idea accelerator in Shoreditch Exchange',
    area: 'Shoreditch',
    access_type: 'invite',
    crowd_tags: ['founders', 'researchers'],
    tags: ['studio', 'events'],
    featured: false,
  },
  {
    slug: 'francis-crick-institute',
    name: 'Francis Crick Institute',
    strapline: "1,500-person biomedical research centre at King's Cross",
    area: "King's Cross",
    access_type: 'members',
    crowd_tags: ['researchers'],
    tags: ['lab'],
    featured: false,
  },
  {
    slug: 'flight-story',
    name: 'Flight Story',
    strapline: 'Media and investment firm led by Steven Bartlett, with community space',
    area: 'Shoreditch',
    access_type: 'invite',
    crowd_tags: ['founders', 'operators', 'artists'],
    tags: ['studio', 'events'],
    featured: false,
  },
  {
    slug: 'founders-factory',
    name: 'Founders Factory',
    strapline: 'Startup studio and accelerator, part of Founders Forum and Firstminute Capital',
    area: 'Holborn',
    access_type: 'invite',
    crowd_tags: ['founders', 'operators'],
    tags: ['studio', 'events'],
    website: 'https://foundersfactory.com',
    featured: false,
  },
  {
    slug: 'london-institute-healthcare-engineering',
    name: 'London Institute for Healthcare Engineering',
    strapline: "King's College MedTech venture builder",
    area: 'Waterloo',
    access_type: 'invite',
    crowd_tags: ['researchers', 'founders'],
    tags: ['lab', 'studio'],
    website: 'https://lihe.org.uk',
    featured: false,
  },
  {
    slug: 'level-39',
    name: 'Level 39',
    strapline: "Europe's largest tech accelerator space for finance, retail and smart city tech",
    area: 'Canary Wharf',
    access_type: 'members',
    crowd_tags: ['founders', 'techies'],
    tags: ['coworking', 'events', 'studio'],
    website: 'https://www.level39.co',
    featured: false,
  },
  {
    slug: 'the-trampery',
    name: 'The Trampery',
    strapline: 'Creative and tech workspace communities in Shoreditch and Canning Town',
    area: 'Shoreditch',
    access_type: 'members',
    crowd_tags: ['founders', 'designers', 'artists'],
    tags: ['coworking', 'studio', 'events'],
    website: 'https://thetrampery.com',
    featured: false,
  },
  {
    slug: 'bethnal-green-ventures',
    name: 'Bethnal Green Ventures',
    strapline: 'Impact tech accelerator for founders using technology to tackle big social and environmental problems',
    area: 'Shoreditch',
    access_type: 'invite',
    crowd_tags: ['founders', 'researchers'],
    tags: ['studio', 'events'],
    website: 'https://bethnalgreenventures.com',
    featured: false,
  },
  {
    slug: 'wayra-uk',
    name: 'Wayra UK',
    strapline: "Telefónica's startup accelerator for early-stage tech companies",
    area: 'Southwark',
    access_type: 'invite',
    crowd_tags: ['founders', 'techies'],
    tags: ['studio', 'events'],
    website: 'https://wayra.com/uk',
    featured: false,
  },
  {
    slug: 'bootstrap-company',
    name: 'Bootstrap Company',
    strapline: 'Affordable creative and social enterprise workspace in Dalston since 1977',
    area: 'Dalston',
    access_type: 'members',
    crowd_tags: ['artists', 'designers', 'founders'],
    tags: ['coworking', 'studio', 'events'],
    website: 'https://www.bootstrapcompany.co.uk',
    featured: false,
  },
  {
    slug: 'cockpit-arts',
    name: 'Cockpit Arts',
    strapline: 'Incubator for designer-makers in Holborn and Deptford',
    area: 'Holborn',
    access_type: 'members',
    crowd_tags: ['designers', 'artists'],
    tags: ['studio', 'lab'],
    website: 'https://www.cockpitarts.com',
    featured: false,
  },
  {
    slug: 'hackney-downs-studios',
    name: 'Hackney Downs Studios',
    strapline: 'Creative studios, workspace and events venue in Hackney',
    area: 'Hackney',
    access_type: 'members',
    crowd_tags: ['artists', 'designers', 'founders'],
    tags: ['studio', 'coworking', 'events'],
    website: 'https://www.hackneydownsstudios.com',
    featured: false,
  },
  {
    slug: 'blackhorse-workshop',
    name: 'Blackhorse Workshop',
    strapline: 'Public workshop and maker space in Walthamstow with shared tools and digital fabrication',
    area: 'Walthamstow',
    access_type: 'members',
    crowd_tags: ['designers', 'artists', 'techies'],
    tags: ['lab', 'studio'],
    website: 'https://blackhorseworkshop.co.uk',
    featured: false,
  },
  {
    slug: 'collider',
    name: 'Collider',
    strapline: 'Accelerator programme for adtech and martech startups',
    area: 'Shoreditch',
    access_type: 'invite',
    crowd_tags: ['founders', 'techies'],
    tags: ['studio', 'events'],
    website: 'https://www.collider.io',
    featured: false,
  },
  {
    slug: 'better-space',
    name: 'Better Space',
    strapline: 'Social enterprise coworking space in Farringdon',
    area: 'Farringdon',
    access_type: 'members',
    crowd_tags: ['founders', 'designers'],
    tags: ['coworking'],
    website: 'https://www.betterspace.uk',
    featured: false,
  },
  {
    slug: 'lifefabs',
    name: 'LifeFabs',
    strapline: 'Open access bio lab with fellows and teaching programmes',
    area: 'London',
    access_type: 'open',
    crowd_tags: ['researchers', 'founders'],
    tags: ['lab'],
    featured: false,
  },
  {
    slug: '50-years-soho-square',
    name: '50 Years (Soho Square)',
    strapline: 'Event and community space for science founders, home of the 50 Years VC',
    area: 'Soho',
    access_type: 'invite',
    crowd_tags: ['founders', 'researchers'],
    tags: ['events', 'coworking'],
    website: 'https://www.50years.vc',
    featured: false,
  },
]

async function seed() {
  console.log(`Seeding ${SPACES.length} spaces...`)

  const { data, error } = await supabase
    .from('spaces')
    .upsert(SPACES, { onConflict: 'slug' })
    .select('id, name')

  if (error) {
    console.error('Error seeding spaces:', error)
    process.exit(1)
  }

  console.log(`✓ Seeded ${data?.length} spaces`)
  data?.forEach((s) => console.log(`  - ${s.name}`))
}

seed()
