import { createClient } from '@supabase/supabase-js'
import { Database } from '../src/lib/database.types'

const supabase = createClient<Database>(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

type VCInsert = Database['public']['Tables']['vcs']['Insert']

const VCS: VCInsert[] = [
  {
    slug: 'localglobe',
    name: 'LocalGlobe',
    description: 'One of London\'s most active early-stage funds, backing pre-seed and seed founders across Europe. Strong community and operator network.',
    sectors: ['software', 'deeptech', 'founders'],
    stages: ['pre-seed', 'seed'],
    check_min: 500,
    check_max: 3000,
    london_team: true,
    website: 'https://localglobe.vc',
    featured: true,
  },
  {
    slug: 'balderton',
    name: 'Balderton Capital',
    description: 'European Series A and growth investor. One of the largest and most established VC funds in London, backing category-defining companies.',
    sectors: ['software', 'deeptech', 'founders'],
    stages: ['series-a', 'series-b', 'growth'],
    check_min: 10000,
    check_max: 100000,
    london_team: true,
    website: 'https://balderton.com',
    featured: true,
  },
  {
    slug: 'atomico',
    name: 'Atomico',
    description: 'Pan-European VC founded by Skype\'s Niklas Zennström. Invests from Series A through growth, with a particular focus on European tech.',
    sectors: ['software', 'deeptech', 'founders'],
    stages: ['series-a', 'series-b', 'growth'],
    check_min: 10000,
    check_max: 100000,
    london_team: true,
    website: 'https://atomico.com',
    featured: true,
  },
  {
    slug: 'iq-capital',
    name: 'IQ Capital',
    description: 'Deep tech specialist investing in AI, quantum, semiconductors, and advanced engineering. Strong links to UK universities and spinouts.',
    sectors: ['deeptech', 'ai'],
    stages: ['seed', 'series-a'],
    check_min: 1000,
    check_max: 10000,
    london_team: true,
    website: 'https://iqcapital.vc',
    featured: true,
  },
  {
    slug: 'molten-ventures',
    name: 'Molten Ventures',
    description: 'Formerly Draper Esprit. Series B and growth stage pan-European fund investing in high-growth technology companies.',
    sectors: ['software', 'deeptech'],
    stages: ['series-b', 'growth'],
    check_min: 5000,
    check_max: 50000,
    london_team: true,
    website: 'https://molten.vc',
    featured: false,
  },
  {
    slug: 'dawn-capital',
    name: 'Dawn Capital',
    description: 'B2B software specialist. One of Europe\'s leading enterprise and SaaS investors, backing companies from Series A through growth.',
    sectors: ['software'],
    stages: ['series-a', 'series-b'],
    check_min: 5000,
    check_max: 50000,
    london_team: true,
    website: 'https://dawncapital.com',
    featured: false,
  },
  {
    slug: 'octopus-ventures',
    name: 'Octopus Ventures',
    description: 'One of the UK\'s most active VC funds, investing across seed through Series B. Wide sector coverage with particular strength in health and deep tech.',
    sectors: ['software', 'deeptech', 'founders'],
    stages: ['seed', 'series-a', 'series-b'],
    check_min: 1000,
    check_max: 20000,
    london_team: true,
    website: 'https://octopusventures.com',
    featured: false,
  },
  {
    slug: 'amadeus-capital',
    name: 'Amadeus Capital Partners',
    description: 'Deep tech and advanced technology investor with a 25-year track record. Strong in semiconductors, AI, and next-generation computing.',
    sectors: ['deeptech', 'ai'],
    stages: ['seed', 'series-a', 'series-b'],
    check_min: 2000,
    check_max: 20000,
    london_team: true,
    website: 'https://amadeuscapital.com',
    featured: false,
  },
  {
    slug: 'seraphim-space',
    name: 'Seraphim Space',
    description: 'The world\'s leading space tech VC. Backs companies building the new space economy — satellites, launch, Earth observation, and downstream applications.',
    sectors: ['deeptech', 'space'],
    stages: ['seed', 'series-a'],
    check_min: 1000,
    check_max: 15000,
    london_team: true,
    website: 'https://seraphim.vc',
    featured: true,
  },
  {
    slug: 'ip-group',
    name: 'IP Group',
    description: 'University spinout specialist. Partners with Oxford, Cambridge, and other leading universities to commercialise breakthrough science.',
    sectors: ['deeptech'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 10000,
    london_team: true,
    website: 'https://ipgroup.com',
    featured: false,
  },
  {
    slug: 'oxford-science-enterprises',
    name: 'Oxford Science Enterprises',
    description: 'Oxford University\'s dedicated VC arm. Backs spinouts from Oxford across life sciences, deep tech, and quantum computing.',
    sectors: ['deeptech'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 10000,
    london_team: true,
    website: 'https://oxfordscienceenterprises.com',
    featured: false,
  },
  {
    slug: 'cambridge-innovation-capital',
    name: 'Cambridge Innovation Capital',
    description: 'The Cambridge University ecosystem\'s primary VC. Invests in spinouts and deep tech companies emerging from the Cambridge cluster.',
    sectors: ['deeptech'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 10000,
    london_team: true,
    website: 'https://cambridgeinnovationcapital.com',
    featured: false,
  },
  {
    slug: 'ahren-innovation-capital',
    name: 'Ahren Innovation Capital',
    description: 'Deep tech and frontier science investor with a long-term perspective. Focuses on transformational technologies in AI, biotech, and advanced materials.',
    sectors: ['deeptech', 'ai'],
    stages: ['seed', 'series-a'],
    check_min: 1000,
    check_max: 15000,
    london_team: true,
    website: 'https://ahreninnovation.com',
    featured: false,
  },
  {
    slug: 'albion-vc',
    name: 'AlbionVC',
    description: 'UK-focused B2B software investor. Backs enterprise SaaS and tech-enabled services companies from seed through Series B.',
    sectors: ['software'],
    stages: ['seed', 'series-a', 'series-b'],
    check_min: 2000,
    check_max: 15000,
    london_team: true,
    website: 'https://albion.vc',
    featured: false,
  },
  {
    slug: 'hummingbird',
    name: 'Hummingbird Ventures',
    description: 'Pan-European early-stage investor with a contrarian, thesis-driven approach. Backs founders building in unexpected places and overlooked markets.',
    sectors: ['software', 'deeptech'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 8000,
    london_team: true,
    website: 'https://hummingbird.vc',
    featured: false,
  },
  {
    slug: 'firstminute-capital',
    name: 'Firstminute Capital',
    description: 'Seed-stage global VC with strong London roots. Run by ex-Skyscanner founders, backed by over 60 unicorn founders as LPs.',
    sectors: ['software', 'founders'],
    stages: ['pre-seed', 'seed'],
    check_min: 500,
    check_max: 5000,
    london_team: true,
    website: 'https://firstminute.capital',
    featured: false,
  },
  {
    slug: 'tdk-ventures',
    name: 'TDK Ventures',
    description: 'Corporate VC arm of TDK. Invests in energy, materials, and hardware startups at the frontier of the physical world.',
    sectors: ['deeptech'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 5000,
    london_team: true,
    website: 'https://tdkventures.com',
    featured: false,
  },
  {
    slug: 'giant-ventures',
    name: 'Giant Ventures',
    description: 'Impact-focused deep tech investor. Backs founders tackling big problems in climate, health, and education with transformative technology.',
    sectors: ['deeptech', 'climate'],
    stages: ['seed', 'series-a'],
    check_min: 500,
    check_max: 5000,
    london_team: true,
    website: 'https://giant.vc',
    featured: false,
  },
  {
    slug: 'blue-wire-capital',
    name: 'Blue Wire Capital',
    description: 'Early-stage generalist investor based in London. Backs ambitious founders building the next generation of technology companies.',
    sectors: ['software', 'deeptech'],
    stages: ['pre-seed', 'seed'],
    check_min: 250,
    check_max: 2000,
    london_team: true,
    website: 'https://bluewire.vc',
    featured: false,
  },
  {
    slug: 'unruly-capital',
    name: 'Unruly Capital',
    description: 'Emerging deep tech fund backing unconventional founders at the earliest stages.',
    sectors: ['deeptech'],
    stages: ['pre-seed', 'seed'],
    check_min: 100,
    check_max: 1000,
    london_team: true,
    website: null,
    featured: false,
  },
  {
    slug: 'prosemino',
    name: 'Prosemino',
    description: 'Climate and science VC fund run by Yen and ERV, backing early-stage founders.',
    sectors: ['climate', 'science'],
    stages: ['pre-seed', 'seed'],
    london_team: true,
    website: 'https://www.prosemino.co.uk',
    featured: false,
  },
  {
    slug: '50-years',
    name: '50 Years',
    description: 'Science-focused VC fund with a house in Soho Square. Backs founders tackling civilisational-scale problems in biotech, climate, and deeptech. Also runs 5050, an equity-free incubator for scientists becoming founders.',
    sectors: ['deeptech', 'climate', 'science'],
    stages: ['pre-seed', 'seed'],
    london_team: true,
    website: 'https://www.50years.vc',
    featured: false,
  },
]

async function seed() {
  console.log(`Seeding ${VCS.length} VCs...`)

  const { data, error } = await supabase
    .from('vcs')
    .upsert(VCS, { onConflict: 'slug' })
    .select('id, name')

  if (error) {
    console.error('Error seeding VCs:', error)
    process.exit(1)
  }

  console.log(`✓ Seeded ${data?.length} VCs`)
  data?.forEach((vc) => console.log(`  - ${vc.name}`))
}

seed()
